name: native_app_list
description: A plugin to get the list of installed apps.
version: 0.0.1
homepage: https://example.com

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.native_app_list
        pluginClass: NativeAppListPlugin